### ISSUE TITLE
Translation Progress Checklist

### ISSUE THREAD

**Issue by elijahhampton** [solidity-docs/es-spanish#1]
# Translation Progress Checklist

## Maintainers List

["DanielMart-tech", "elijahhampton", "mektigboy"]

## For New Translators

To translate a page:

Check that no one else has claimed your page in the checklist and comments below.
Comment below with the name of the page you would like to translate. Please take only one page at a time.
Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical or Solidity/Ethereum-specific terms. **We will update the README to include the glossary, style guide and other important information soon.**

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

- [x] README (@mektigboy ) #2 

When PRs are merged, make sure to mark that page as completed!

- [x] README 

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

### Basics

- [x] index
- [ ] intro-to-smart-contracts 
- [x] installing-solidity
- [x] solidity-by-example 

### Language Description

- [x] layout_of_source_files
- [x] structure of a contract
- [x] types
- [x] units_and-global_variables
- [x] control_structures
- [x] contracts
- [x] assembly
- [x] cheatsheet
- [x] grammar
- [x] language_influences

### Contracts

- [x] abstract_contracts
- [x] constant_state_variables
- [ ] creating_contracts
- [x] errors
- [ ] events
- [ ] function-modifiers
- [ ] functions
- [ ] inheritance
- [x] interfaces
- [ ] libraries
- [x] using_for
- [ ] visibility_and_getters

### Examples

- [ ] blind_acution
- [ ] micropayment
- [ ] modular
- [ ] safe_remote
- [ ] voting

### Internals

* [ ] layout_in_storage
* [x] layout_in_memory
* [x] layout_in_calldata
* [x] variable_cleanup
* [x] source_mappings
* [ ] optimizer

### Types

- [ ] conversion
- [x] mapping_types
- [ ] operator_precedence_table
- [ ] operators
- [x] reference_types
- [ ] value-types

### Additional Material

* [ ] yul
* [x] natspec_format 
* [x] security_considerations
* [x] common_patterns

## Next Steps

These are the next most important translations, ordered by importance:

### Additional Material

- [ ] contributing
- [ ] using_the_compiler
- [x] 080-breaking-changes
- [ ] 070-breaking-changes
- [ ] 060-breaking-changes
- [ ] 050-breaking-changes
- [ ] metadata
- [ ] abi_spec
- [x] resources
- [x] bugs
- [x] brand_guide
- [x] credits_and_attribution

## Additional Translations

- [ ] style-guide
- [ ] smtchecker
- [ ] path-resolution
- [ ] natspec_format
- [ ] ir_breaking_changes
- [ ] credits_and_attribution
- [ ] analysing_compilation_output

These are not the primary translation targets. We will update this list as progress is made in the repository.

** Coming soon **

**Comment by garosan** [comment]
I can start with the next available page:  installing-solidity

**Comment by natastro** [comment]
I'd be happy to work on units-and-global-variables !

**Comment by garosan** [comment]
I can take layout_in_storage next.

**Comment by garosan** [comment]
Hi @natastro try to join the chat here https://matrix.to/#/#solidity-docs-translations:matrix.org so we can all better coordinate.

**Comment by elijahhampton** [comment]
> I'd be happy to work on units-and-global-variables !

Assigned

**Comment by elijahhampton** [comment]
@garosan Are you still working on layout_in_storage? If so, no problem, I was just going to free it up just incase someone else wanted to grab it if not.

**Comment by garosan** [comment]
@elijahhampton Hey man sorry I totally forgot about this, yeah free it up, I'm totally swamped for a couple of months, ty.

**Comment by AndreaFMag** [comment]
Hey @elijahhampton, I'm interested in translating the source_mappings page.

**Comment by elijahhampton** [comment]
@AndreaFMag Okay. I will add your name. Thanks!

**Comment by elijahhampton** [comment]
> Hey @elijahhampton, I'm interested in translating the source_mappings page.

All yours

**Comment by juanjo-suarez** [comment]
Hello @elijahhampton!, I would like to take the /docs/types/reference-types.rst

**Comment by elijahhampton** [comment]
> Hello @elijahhampton!, I would like to take the /docs/types/reference-types.rst

Good deal. All yours.

**Comment by cmayorga** [comment]
Hey @elijahhampton , i would like to take /docs/080-breaking-changes by now

**Comment by elijahhampton** [comment]
> Hey @elijahhampton , i would like to take /docs/080-breaking-changes by now

You got it.

**Comment by AndreaFMag** [comment]
Hey @elijahhampton  I'd like to take the using_for page next

**Comment by elijahhampton** [comment]
> Hey @elijahhampton  I'd like to take the using_for page next

Added
